<?php

namespace AppBundle\Repository;

/**
 * VaultGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaultGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVaultGroupByName($name){
        return $this->getEntityManager()
                ->createQuery('SELECT vg FROM AppBundle:VaultGroup vg WHERE vg.name=:name')
                ->setParameter('name',$name)
                ->getResult();
    }
}
